"""baseline: all spec §11 tables + player_id_mapping + cache_entry

Revision ID: 790295b8e4e6
Revises: 
Create Date: 2026-10-04 17:41:20.309704

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '790295b8e4e6'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm")
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cache_entry',
    sa.Column('key', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('value', sa.JSON(), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('canonical_player',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('last_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('full_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('normalized_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('position', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('nfl_team_code', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('active_status', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('injury_status', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('gsis_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('sleeper_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('espn_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('yahoo_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('fleaflicker_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('stats_provider_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('search_rank', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sleeper_id')
    )
    op.create_index(op.f('ix_canonical_player_espn_id'), 'canonical_player', ['espn_id'], unique=False)
    op.create_index(op.f('ix_canonical_player_gsis_id'), 'canonical_player', ['gsis_id'], unique=False)
    op.create_index(op.f('ix_canonical_player_nfl_team_code'), 'canonical_player', ['nfl_team_code'], unique=False)
    op.create_index(op.f('ix_canonical_player_normalized_name'), 'canonical_player', ['normalized_name'], unique=False)
    op.create_index('ix_canonical_player_normalized_name_trgm', 'canonical_player', ['normalized_name'], unique=False, postgresql_using='gin', postgresql_ops={'normalized_name': 'gin_trgm_ops'})
    op.create_index(op.f('ix_canonical_player_position'), 'canonical_player', ['position'], unique=False)
    op.create_index(op.f('ix_canonical_player_yahoo_id'), 'canonical_player', ['yahoo_id'], unique=False)
    op.create_table('nfl_game',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('external_game_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('season', sa.Integer(), nullable=False),
    sa.Column('week', sa.Integer(), nullable=False),
    sa.Column('kickoff_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('home_team', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('away_team', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('home_score', sa.Integer(), nullable=True),
    sa.Column('away_score', sa.Integer(), nullable=True),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status_detail', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('quarter', sa.Integer(), nullable=True),
    sa.Column('clock', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('broadcaster', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('external_game_id')
    )
    op.create_index('ix_nfl_game_season_week', 'nfl_game', ['season', 'week'], unique=False)
    op.create_table('user',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=False)
    op.create_table('player_game_stats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=True),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('season', sa.Integer(), nullable=False),
    sa.Column('week', sa.Integer(), nullable=False),
    sa.Column('raw_stats_json', sa.JSON(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['nfl_game.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['player_id'], ['canonical_player.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('player_id', 'season', 'week')
    )
    op.create_index(op.f('ix_player_game_stats_game_id'), 'player_game_stats', ['game_id'], unique=False)
    op.create_index(op.f('ix_player_game_stats_player_id'), 'player_game_stats', ['player_id'], unique=False)
    op.create_table('player_id_mapping',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('provider', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('external_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('method', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['player_id'], ['canonical_player.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider', 'external_id')
    )
    op.create_index(op.f('ix_player_id_mapping_player_id'), 'player_id_mapping', ['player_id'], unique=False)
    op.create_table('provider_connection',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('provider', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('external_account_identifier', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('encrypted_access_token', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('encrypted_refresh_token', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('token_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('scopes', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'provider')
    )
    op.create_index(op.f('ix_provider_connection_user_id'), 'provider_connection', ['user_id'], unique=False)
    op.create_table('scoring_profile',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('league_id', sa.Integer(), nullable=True),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('preset', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('scoring_json', sa.JSON(), nullable=False),
    sa.Column('unsupported_json', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scoring_profile_league_id'), 'scoring_profile', ['league_id'], unique=False)
    op.create_index(op.f('ix_scoring_profile_user_id'), 'scoring_profile', ['user_id'], unique=False)
    op.create_table('fantasy_league',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('provider', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('external_league_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('season', sa.Integer(), nullable=False),
    sa.Column('current_week', sa.Integer(), nullable=True),
    sa.Column('num_teams', sa.Integer(), nullable=True),
    sa.Column('scoring_profile_id', sa.Integer(), nullable=True),
    sa.Column('selected_team_id', sa.Integer(), nullable=True),
    sa.Column('last_synced_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['scoring_profile_id'], ['scoring_profile.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'provider', 'external_league_id')
    )
    op.create_index(op.f('ix_fantasy_league_user_id'), 'fantasy_league', ['user_id'], unique=False)
    op.create_table('fantasy_team',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('league_id', sa.Integer(), nullable=True),
    sa.Column('provider', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('external_team_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('owner_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('is_user_team', sa.Boolean(), nullable=False),
    sa.Column('is_manual', sa.Boolean(), nullable=False),
    sa.Column('scoring_profile_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['league_id'], ['fantasy_league.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['scoring_profile_id'], ['scoring_profile.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fantasy_team_league_id'), 'fantasy_team', ['league_id'], unique=False)
    op.create_index(op.f('ix_fantasy_team_user_id'), 'fantasy_team', ['user_id'], unique=False)
    op.create_table('fantasy_matchup',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('league_id', sa.Integer(), nullable=False),
    sa.Column('season', sa.Integer(), nullable=False),
    sa.Column('week', sa.Integer(), nullable=False),
    sa.Column('user_team_id', sa.Integer(), nullable=False),
    sa.Column('opponent_team_id', sa.Integer(), nullable=True),
    sa.Column('user_score', sa.Float(), nullable=True),
    sa.Column('opponent_score', sa.Float(), nullable=True),
    sa.Column('user_projected', sa.Float(), nullable=True),
    sa.Column('opponent_projected', sa.Float(), nullable=True),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('fetched_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['league_id'], ['fantasy_league.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['opponent_team_id'], ['fantasy_team.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_team_id'], ['fantasy_team.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('league_id', 'season', 'week', 'user_team_id')
    )
    op.create_index(op.f('ix_fantasy_matchup_league_id'), 'fantasy_matchup', ['league_id'], unique=False)
    op.create_table('roster_snapshot',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fantasy_team_id', sa.Integer(), nullable=False),
    sa.Column('season', sa.Integer(), nullable=False),
    sa.Column('week', sa.Integer(), nullable=False),
    sa.Column('fetched_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['fantasy_team_id'], ['fantasy_team.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('fantasy_team_id', 'season', 'week')
    )
    op.create_index(op.f('ix_roster_snapshot_fantasy_team_id'), 'roster_snapshot', ['fantasy_team_id'], unique=False)
    op.create_table('roster_entry',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('roster_snapshot_id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=True),
    sa.Column('slot', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('is_starter', sa.Boolean(), nullable=False),
    sa.Column('is_bench', sa.Boolean(), nullable=False),
    sa.Column('is_ir', sa.Boolean(), nullable=False),
    sa.Column('provider_player_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('provider_player_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('provider_position', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('provider_nfl_team', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('provider_status', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['player_id'], ['canonical_player.id'], ),
    sa.ForeignKeyConstraint(['roster_snapshot_id'], ['roster_snapshot.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_roster_entry_roster_snapshot_id'), 'roster_entry', ['roster_snapshot_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_roster_entry_roster_snapshot_id'), table_name='roster_entry')
    op.drop_table('roster_entry')
    op.drop_index(op.f('ix_roster_snapshot_fantasy_team_id'), table_name='roster_snapshot')
    op.drop_table('roster_snapshot')
    op.drop_index(op.f('ix_fantasy_matchup_league_id'), table_name='fantasy_matchup')
    op.drop_table('fantasy_matchup')
    op.drop_index(op.f('ix_fantasy_team_user_id'), table_name='fantasy_team')
    op.drop_index(op.f('ix_fantasy_team_league_id'), table_name='fantasy_team')
    op.drop_table('fantasy_team')
    op.drop_index(op.f('ix_fantasy_league_user_id'), table_name='fantasy_league')
    op.drop_table('fantasy_league')
    op.drop_index(op.f('ix_scoring_profile_user_id'), table_name='scoring_profile')
    op.drop_index(op.f('ix_scoring_profile_league_id'), table_name='scoring_profile')
    op.drop_table('scoring_profile')
    op.drop_index(op.f('ix_provider_connection_user_id'), table_name='provider_connection')
    op.drop_table('provider_connection')
    op.drop_index(op.f('ix_player_id_mapping_player_id'), table_name='player_id_mapping')
    op.drop_table('player_id_mapping')
    op.drop_index(op.f('ix_player_game_stats_player_id'), table_name='player_game_stats')
    op.drop_index(op.f('ix_player_game_stats_game_id'), table_name='player_game_stats')
    op.drop_table('player_game_stats')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    op.drop_index('ix_nfl_game_season_week', table_name='nfl_game')
    op.drop_table('nfl_game')
    op.drop_index(op.f('ix_canonical_player_yahoo_id'), table_name='canonical_player')
    op.drop_index(op.f('ix_canonical_player_position'), table_name='canonical_player')
    op.drop_index('ix_canonical_player_normalized_name_trgm', table_name='canonical_player', postgresql_using='gin', postgresql_ops={'normalized_name': 'gin_trgm_ops'})
    op.drop_index(op.f('ix_canonical_player_normalized_name'), table_name='canonical_player')
    op.drop_index(op.f('ix_canonical_player_nfl_team_code'), table_name='canonical_player')
    op.drop_index(op.f('ix_canonical_player_gsis_id'), table_name='canonical_player')
    op.drop_index(op.f('ix_canonical_player_espn_id'), table_name='canonical_player')
    op.drop_table('canonical_player')
    op.drop_table('cache_entry')
    # ### end Alembic commands ###
